# flux HelmChart to grab nginx ingress controller chart

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 2.4.x
  interval: 5h
  sourceRef:
    kind: HelmRepository
    name: nginx